repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-added-large-files
      exclude: ^img/
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
      files: \.(py|rst|sh|yaml|yml)$
    - id: mixed-line-ending
    - id: trailing-whitespace
      files: \.(py|rst|sh|yaml|yml)$
- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
    - id: isort
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    additional_dependencies: [
      'flake8-blind-except',
      'flake8-bugbear',
      'flake8-comprehensions',
      'flake8-implicit-str-concat',
      'pydocstyle>=5.0.0',
    ]
