# ===================================================================================== #
#           GitHub Actions configuration file for an AWS Glue ETL application           #
#                                                                                       #
# This workflow will:                                                                   #
#   1. Create AWS resources for the production environment using Terraform.             #
# ===================================================================================== #

name: on IaC PUSH to [main]

on:
  push:
    branches: [main]
    paths:
      - "infrastructure/**"
      - '.github/workflows/**'

jobs:

# ===================================================================================== #
#               CREATE THE AWS RESOURCES FOR THE PRODUCTION ENVIRONMENT                 #
# ===================================================================================== #
  terraform-production-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform style check
        run: terraform fmt -check -recursive ./infrastructure
      - name: Terraform validate
        run: terraform -chdir ./infrastructure validate
      - name: Terraform init
        run: terraform -chdir ./infrastructure/production init
      - name: Terraform plan
        run: terraform -chdir ./infrastructure/production plan
      - name: Terraform apply
        run: terraform -chdir ./infrastructure/production -input=false apply
